source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'ScrollLoopView_Example', :exclusive => true do
  pod "ScrollLoopView", :path => "../"
end

target 'ScrollLoopView_Tests', :exclusive => true do
  pod "ScrollLoopView", :path => "../"

  
end
